os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9
env:
  - TOOLCHAINS=swift
install:
  - wget https://swift.org/builds/swift-4.2-branch/xcode/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-15-a/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-15-a-osx.pkg
  - sudo installer -pkg swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-15-a-osx.pkg -target /
  - export PATH="/Library/Developer/Toolchains/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-15-a.xctoolchain/usr/bin:$PATH"
script:
  - swift build
  - swift test
